// This file is automatically generated from your CSS. Any edits will be overwritten.
export const form: string;
export const inputRow: string;
export const submitRow: string;
export const distance: string;
export const spacer: string;
