// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    'hamburger-menu-button': string;
    'header': string;
    'header-container': string;
    'links': string;
    'menu-line': string;
    'nav': string;
    'off-screen-container': string;
    'open': string;
    'overlay': string;
    'title': string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
