// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const headerContainer: string;
export const title: string;
export const nav: string;
export const active: string;
export const links: string;
export const offScreenContainer: string;
export const open: string;
export const overlay: string;
export const hamburgerMenuButton: string;
export const menuLine: string;
