// This file is automatically generated from your CSS. Any edits will be overwritten.
export const groupContainer: string;
export const inputContainer: string;
export const small: string;
export const medium: string;
