// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    'distance-label': string;
    'finish-time': string;
    'race-time': string;
    'split-row': string;
    'splits-table': string;
    'title': string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
