// This file is automatically generated from your CSS. Any edits will be overwritten.
export const title: string;
export const splitsTable: string;
export const raceTime: string;
export const splitRow: string;
export const distanceLabel: string;
export const finishTime: string;
