// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace GlobalCssNamespace {
  export interface IGlobalCss {
    'container': string;
    'mobile-hidden': string;
    'mobile-only': string;
  }
}

declare const GlobalCssModule: GlobalCssNamespace.IGlobalCss;

export = GlobalCssModule;
